DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS states;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS comments;

CREATE TABLE roles
(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
title TEXT NOT NULL UNIQUE
);

CREATE TABLE rules (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
title TEXT NOT NULL UNIQUE
);

CREATE TABLE roles_rules (
role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
rule_id BIGINT NOT NULL REFERENCES rules(id) ON DELETE CASCADE,
PRIMARY KEY (role_id, rule_id)
);

CREATE TABLE users
(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
login TEXT NOT NULL UNIQUE CHECK (char_length(login) >= 3),
password_hash TEXT NOT NULL CHECK (char_length(password_hash) >= 8),
email TEXT NOT NULL UNIQUE,
role_id BIGINT NOT NULL REFERENCES roles(id),
created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE states
(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
title TEXT NOT NULL UNIQUE
);

CREATE TABLE categories
(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
title TEXT NOT NULL UNIQUE
);

CREATE TABLE items
(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
title TEXT NOT NULL,
description TEXT NOT NULL,
author_id BIGINT NOT NULL REFERENCES users(id),
state_id BIGINT NOT NULL REFERENCES states(id),
category_id BIGINT NOT NULL REFERENCES categories(id),
created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE comments
(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
text TEXT NOT NULL,
item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
author_id BIGINT NOT NULL REFERENCES users(id)
);

CREATE TABLE attachs (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
file_name TEXT NOT NULL,
file_size BIGINT NOT NULL CHECK (file_size > 0),
created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);